/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.scottcaruso.currencyconverter;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int au=0x7f020000;
        public static final int ca=0x7f020001;
        public static final int ch=0x7f020002;
        public static final int eu=0x7f020003;
        public static final int gb=0x7f020004;
        public static final int hk=0x7f020005;
        public static final int ic_launcher=0x7f020006;
        public static final int jp=0x7f020007;
        public static final int nz=0x7f020008;
        public static final int se=0x7f020009;
        public static final int sk=0x7f02000a;
    }
    public static final class id {
        public static final int action_settings=0x7f080016;
        public static final int ausdol_amt=0x7f080005;
        public static final int ausdol_label=0x7f080004;
        public static final int can_amt=0x7f080007;
        public static final int can_label=0x7f080006;
        public static final int dollar_amt=0x7f080001;
        public static final int dollar_label=0x7f080000;
        public static final int euro_amt=0x7f080003;
        public static final int euro_label=0x7f080002;
        public static final int hk_amt=0x7f080009;
        public static final int hk_label=0x7f080008;
        public static final int jpn_amt=0x7f080015;
        public static final int jpn_label=0x7f080014;
        public static final int nz_label=0x7f08000a;
        public static final int nzl_amt=0x7f08000b;
        public static final int sko_amt=0x7f080013;
        public static final int sko_label=0x7f080012;
        public static final int swe_amt=0x7f08000f;
        public static final int swe_label=0x7f08000e;
        public static final int swz_amt=0x7f080011;
        public static final int swz_label=0x7f080010;
        public static final int uk_amt=0x7f08000d;
        public static final int uk_label=0x7f08000c;
    }
    public static final class layout {
        public static final int activity_currency=0x7f030000;
    }
    public static final class menu {
        public static final int currency=0x7f070000;
    }
    public static final class string {
        public static final int _0_00=0x7f05000a;
        public static final int action_settings=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int aus=0x7f05000b;
        public static final int aussie_amount=0x7f050008;
        public static final int australian_dollars=0x7f050007;
        public static final int can=0x7f05000c;
        public static final int eur=0x7f050009;
        public static final int euro_amt_=0x7f050006;
        public static final int euros=0x7f050005;
        public static final int hello_world=0x7f050002;
        public static final int hk=0x7f05000d;
        public static final int nzl=0x7f05000e;
        public static final int placeholder_dollars=0x7f050004;
        public static final int swe=0x7f050010;
        public static final int swz=0x7f050011;
        public static final int u_s_dollars=0x7f050003;
        public static final int uk=0x7f05000f;
        public static final int won=0x7f050012;
        public static final int yen=0x7f050013;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
